/*
* generated by Xtext
*/
package fr.enseeiht.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.enseeiht.services.PDLXGrammarAccess;

public class PDLXParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PDLXGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.enseeiht.parser.antlr.internal.InternalPDLXParser createParser(XtextTokenStream stream) {
		return new fr.enseeiht.parser.antlr.internal.InternalPDLXParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Process";
	}
	
	public PDLXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PDLXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
