/*
* generated by Xtext
*/
package fr.enseeiht;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PDLXUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.enseeiht.ui.internal.PDLXActivator.getInstance().getInjector("fr.enseeiht.PDLX");
	}
	
}
