/*
 * generated by Xtext
 */
package fr.enseeiht;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PDLXRuntimeModule extends fr.enseeiht.AbstractPDLXRuntimeModule {

}
