/*
* generated by Xtext
*/

package fr.enseeiht.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PDLXGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cProcessElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProcessElementsProcessElementParserRuleCall_3_0 = (RuleCall)cProcessElementsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Process:
		//	"process" name=ID "{" processElements+=ProcessElement* "}";
		public ParserRule getRule() { return rule; }

		//"process" name=ID "{" processElements+=ProcessElement* "}"
		public Group getGroup() { return cGroup; }

		//"process"
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//processElements+=ProcessElement*
		public Assignment getProcessElementsAssignment_3() { return cProcessElementsAssignment_3; }

		//ProcessElement
		public RuleCall getProcessElementsProcessElementParserRuleCall_3_0() { return cProcessElementsProcessElementParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ProcessElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ProcessElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cWorkDefinitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWorkSequenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGuidanceParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRessourceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cNeedParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cNeedSetParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//ProcessElement:
		//	WorkDefinition | WorkSequence | Guidance | Ressource | Need | NeedSet;
		public ParserRule getRule() { return rule; }

		//WorkDefinition | WorkSequence | Guidance | Ressource | Need | NeedSet
		public Alternatives getAlternatives() { return cAlternatives; }

		//WorkDefinition
		public RuleCall getWorkDefinitionParserRuleCall_0() { return cWorkDefinitionParserRuleCall_0; }

		//WorkSequence
		public RuleCall getWorkSequenceParserRuleCall_1() { return cWorkSequenceParserRuleCall_1; }

		//Guidance
		public RuleCall getGuidanceParserRuleCall_2() { return cGuidanceParserRuleCall_2; }

		//Ressource
		public RuleCall getRessourceParserRuleCall_3() { return cRessourceParserRuleCall_3; }

		//Need
		public RuleCall getNeedParserRuleCall_4() { return cNeedParserRuleCall_4; }

		//NeedSet
		public RuleCall getNeedSetParserRuleCall_5() { return cNeedSetParserRuleCall_5; }
	}

	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WorkDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWdKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//WorkDefinition:
		//	"wd" name=ID;
		public ParserRule getRule() { return rule; }

		//"wd" name=ID
		public Group getGroup() { return cGroup; }

		//"wd"
		public Keyword getWdKeyword_0() { return cWdKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class RessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ressource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuantityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuantityINTTerminalRuleCall_3_0 = (RuleCall)cQuantityAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Ressource:
		//	"r" name=ID "(" quantity=INT ")";
		public ParserRule getRule() { return rule; }

		//"r" name=ID "(" quantity=INT ")"
		public Group getGroup() { return cGroup; }

		//"r"
		public Keyword getRKeyword_0() { return cRKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//quantity=INT
		public Assignment getQuantityAssignment_3() { return cQuantityAssignment_3; }

		//INT
		public RuleCall getQuantityINTTerminalRuleCall_3_0() { return cQuantityINTTerminalRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class NeedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Need");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRessourceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRessourceRessourceCrossReference_1_0 = (CrossReference)cRessourceAssignment_1.eContents().get(0);
		private final RuleCall cRessourceRessourceIDTerminalRuleCall_1_0_1 = (RuleCall)cRessourceRessourceCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuantityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuantityINTTerminalRuleCall_3_0 = (RuleCall)cQuantityAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cSetKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNeedSetAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cNeedSetNeedSetCrossReference_6_0 = (CrossReference)cNeedSetAssignment_6.eContents().get(0);
		private final RuleCall cNeedSetNeedSetIDTerminalRuleCall_6_0_1 = (RuleCall)cNeedSetNeedSetCrossReference_6_0.eContents().get(1);
		
		//Need:
		//	"n" ressource=[Ressource] "(" quantity=INT ")" "set" needSet=[NeedSet];
		public ParserRule getRule() { return rule; }

		//"n" ressource=[Ressource] "(" quantity=INT ")" "set" needSet=[NeedSet]
		public Group getGroup() { return cGroup; }

		//"n"
		public Keyword getNKeyword_0() { return cNKeyword_0; }

		//ressource=[Ressource]
		public Assignment getRessourceAssignment_1() { return cRessourceAssignment_1; }

		//[Ressource]
		public CrossReference getRessourceRessourceCrossReference_1_0() { return cRessourceRessourceCrossReference_1_0; }

		//ID
		public RuleCall getRessourceRessourceIDTerminalRuleCall_1_0_1() { return cRessourceRessourceIDTerminalRuleCall_1_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//quantity=INT
		public Assignment getQuantityAssignment_3() { return cQuantityAssignment_3; }

		//INT
		public RuleCall getQuantityINTTerminalRuleCall_3_0() { return cQuantityINTTerminalRuleCall_3_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }

		//"set"
		public Keyword getSetKeyword_5() { return cSetKeyword_5; }

		//needSet=[NeedSet]
		public Assignment getNeedSetAssignment_6() { return cNeedSetAssignment_6; }

		//[NeedSet]
		public CrossReference getNeedSetNeedSetCrossReference_6_0() { return cNeedSetNeedSetCrossReference_6_0; }

		//ID
		public RuleCall getNeedSetNeedSetIDTerminalRuleCall_6_0_1() { return cNeedSetNeedSetIDTerminalRuleCall_6_0_1; }
	}

	public class NeedSetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NeedSet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cWdKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cWdAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cWdWorkDefinitionCrossReference_3_0 = (CrossReference)cWdAssignment_3.eContents().get(0);
		private final RuleCall cWdWorkDefinitionIDTerminalRuleCall_3_0_1 = (RuleCall)cWdWorkDefinitionCrossReference_3_0.eContents().get(1);
		
		//NeedSet:
		//	"set" name=ID "wd" wd=[WorkDefinition];
		public ParserRule getRule() { return rule; }

		//"set" name=ID "wd" wd=[WorkDefinition]
		public Group getGroup() { return cGroup; }

		//"set"
		public Keyword getSetKeyword_0() { return cSetKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"wd"
		public Keyword getWdKeyword_2() { return cWdKeyword_2; }

		//wd=[WorkDefinition]
		public Assignment getWdAssignment_3() { return cWdAssignment_3; }

		//[WorkDefinition]
		public CrossReference getWdWorkDefinitionCrossReference_3_0() { return cWdWorkDefinitionCrossReference_3_0; }

		//ID
		public RuleCall getWdWorkDefinitionIDTerminalRuleCall_3_0_1() { return cWdWorkDefinitionIDTerminalRuleCall_3_0_1; }
	}

	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLinkTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_1_0 = (RuleCall)cLinkTypeAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPredecessorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_3_0 = (CrossReference)cPredecessorAssignment_3.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionIDTerminalRuleCall_3_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_3_0.eContents().get(1);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSuccessorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_5_0 = (CrossReference)cSuccessorAssignment_5.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionIDTerminalRuleCall_5_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_5_0.eContents().get(1);
		
		//WorkSequence:
		//	"ws" linkType=WorkSequenceType "from" predecessor=[WorkDefinition] "to" successor=[WorkDefinition];
		public ParserRule getRule() { return rule; }

		//"ws" linkType=WorkSequenceType "from" predecessor=[WorkDefinition] "to" successor=[WorkDefinition]
		public Group getGroup() { return cGroup; }

		//"ws"
		public Keyword getWsKeyword_0() { return cWsKeyword_0; }

		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_1() { return cLinkTypeAssignment_1; }

		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_1_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_1_0; }

		//"from"
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }

		//predecessor=[WorkDefinition]
		public Assignment getPredecessorAssignment_3() { return cPredecessorAssignment_3; }

		//[WorkDefinition]
		public CrossReference getPredecessorWorkDefinitionCrossReference_3_0() { return cPredecessorWorkDefinitionCrossReference_3_0; }

		//ID
		public RuleCall getPredecessorWorkDefinitionIDTerminalRuleCall_3_0_1() { return cPredecessorWorkDefinitionIDTerminalRuleCall_3_0_1; }

		//"to"
		public Keyword getToKeyword_4() { return cToKeyword_4; }

		//successor=[WorkDefinition]
		public Assignment getSuccessorAssignment_5() { return cSuccessorAssignment_5; }

		//[WorkDefinition]
		public CrossReference getSuccessorWorkDefinitionCrossReference_5_0() { return cSuccessorWorkDefinitionCrossReference_5_0; }

		//ID
		public RuleCall getSuccessorWorkDefinitionIDTerminalRuleCall_5_0_1() { return cSuccessorWorkDefinitionIDTerminalRuleCall_5_0_1; }
	}

	public class GuidanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Guidance");
		private final Assignment cTextAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_0 = (RuleCall)cTextAssignment.eContents().get(0);
		
		//Guidance:
		//	text=STRING;
		public ParserRule getRule() { return rule; }

		//text=STRING
		public Assignment getTextAssignment() { return cTextAssignment; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_0() { return cTextSTRINGTerminalRuleCall_0; }
	}
	
	
	public class WorkSequenceTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStart2startEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStart2startS2sKeyword_0_0 = (Keyword)cStart2startEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinish2startEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinish2startF2sKeyword_1_0 = (Keyword)cFinish2startEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStart2finishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStart2finishS2fKeyword_2_0 = (Keyword)cStart2finishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinish2finishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinish2finishF2fKeyword_3_0 = (Keyword)cFinish2finishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType:
		//	start2start="s2s" | finish2start="f2s" | start2finish="s2f" | finish2finish="f2f";
		public EnumRule getRule() { return rule; }

		//start2start="s2s" | finish2start="f2s" | start2finish="s2f" | finish2finish="f2f"
		public Alternatives getAlternatives() { return cAlternatives; }

		//start2start="s2s"
		public EnumLiteralDeclaration getStart2startEnumLiteralDeclaration_0() { return cStart2startEnumLiteralDeclaration_0; }

		//"s2s"
		public Keyword getStart2startS2sKeyword_0_0() { return cStart2startS2sKeyword_0_0; }

		//finish2start="f2s"
		public EnumLiteralDeclaration getFinish2startEnumLiteralDeclaration_1() { return cFinish2startEnumLiteralDeclaration_1; }

		//"f2s"
		public Keyword getFinish2startF2sKeyword_1_0() { return cFinish2startF2sKeyword_1_0; }

		//start2finish="s2f"
		public EnumLiteralDeclaration getStart2finishEnumLiteralDeclaration_2() { return cStart2finishEnumLiteralDeclaration_2; }

		//"s2f"
		public Keyword getStart2finishS2fKeyword_2_0() { return cStart2finishS2fKeyword_2_0; }

		//finish2finish="f2f"
		public EnumLiteralDeclaration getFinish2finishEnumLiteralDeclaration_3() { return cFinish2finishEnumLiteralDeclaration_3; }

		//"f2f"
		public Keyword getFinish2finishF2fKeyword_3_0() { return cFinish2finishF2fKeyword_3_0; }
	}
	
	private ProcessElements pProcess;
	private ProcessElementElements pProcessElement;
	private WorkDefinitionElements pWorkDefinition;
	private RessourceElements pRessource;
	private NeedElements pNeed;
	private NeedSetElements pNeedSet;
	private WorkSequenceElements pWorkSequence;
	private GuidanceElements pGuidance;
	private WorkSequenceTypeElements unknownRuleWorkSequenceType;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDLXGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process:
	//	"process" name=ID "{" processElements+=ProcessElement* "}";
	public ProcessElements getProcessAccess() {
		return (pProcess != null) ? pProcess : (pProcess = new ProcessElements());
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}

	//ProcessElement:
	//	WorkDefinition | WorkSequence | Guidance | Ressource | Need | NeedSet;
	public ProcessElementElements getProcessElementAccess() {
		return (pProcessElement != null) ? pProcessElement : (pProcessElement = new ProcessElementElements());
	}
	
	public ParserRule getProcessElementRule() {
		return getProcessElementAccess().getRule();
	}

	//WorkDefinition:
	//	"wd" name=ID;
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return (pWorkDefinition != null) ? pWorkDefinition : (pWorkDefinition = new WorkDefinitionElements());
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}

	//Ressource:
	//	"r" name=ID "(" quantity=INT ")";
	public RessourceElements getRessourceAccess() {
		return (pRessource != null) ? pRessource : (pRessource = new RessourceElements());
	}
	
	public ParserRule getRessourceRule() {
		return getRessourceAccess().getRule();
	}

	//Need:
	//	"n" ressource=[Ressource] "(" quantity=INT ")" "set" needSet=[NeedSet];
	public NeedElements getNeedAccess() {
		return (pNeed != null) ? pNeed : (pNeed = new NeedElements());
	}
	
	public ParserRule getNeedRule() {
		return getNeedAccess().getRule();
	}

	//NeedSet:
	//	"set" name=ID "wd" wd=[WorkDefinition];
	public NeedSetElements getNeedSetAccess() {
		return (pNeedSet != null) ? pNeedSet : (pNeedSet = new NeedSetElements());
	}
	
	public ParserRule getNeedSetRule() {
		return getNeedSetAccess().getRule();
	}

	//WorkSequence:
	//	"ws" linkType=WorkSequenceType "from" predecessor=[WorkDefinition] "to" successor=[WorkDefinition];
	public WorkSequenceElements getWorkSequenceAccess() {
		return (pWorkSequence != null) ? pWorkSequence : (pWorkSequence = new WorkSequenceElements());
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}

	//Guidance:
	//	text=STRING;
	public GuidanceElements getGuidanceAccess() {
		return (pGuidance != null) ? pGuidance : (pGuidance = new GuidanceElements());
	}
	
	public ParserRule getGuidanceRule() {
		return getGuidanceAccess().getRule();
	}

	//enum WorkSequenceType:
	//	start2start="s2s" | finish2start="f2s" | start2finish="s2f" | finish2finish="f2f";
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return (unknownRuleWorkSequenceType != null) ? unknownRuleWorkSequenceType : (unknownRuleWorkSequenceType = new WorkSequenceTypeElements());
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
