/*
* generated by Xtext
*/
package fr.enseeiht.ui.contentassist;

import fr.enseeiht.ui.contentassist.AbstractPETRIProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PETRIProposalProvider extends AbstractPETRIProposalProvider {

}
