/*
* generated by Xtext
*/
package fr.enseeiht.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.enseeiht.services.PETRIGrammarAccess;

public class PETRIParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PETRIGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.enseeiht.parser.antlr.internal.InternalPETRIParser createParser(XtextTokenStream stream) {
		return new fr.enseeiht.parser.antlr.internal.InternalPETRIParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PetriNet";
	}
	
	public PETRIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PETRIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
