/*
 * generated by Xtext
 */
package fr.enseeiht.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PETRIUiModule extends fr.enseeiht.ui.AbstractPETRIUiModule {
	public PETRIUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
